### ISSUE TITLE
connect loop

### ISSUE THREAD

**Issue by rp3u** [powerman/perl-AnyEvent-DBI-MySQL#1]
Let's initialize some connections:

```
	for (0..$DB_conns_max) {
		my $dbh = AnyEvent::DBI::MySQL->connect($dsn, "username", "pwd");
		$dbh->{HandleError} = sub { ... };
		$dbh->{mysql_auto_reconnect} = 1;
		$DB_conns[$_] = ();
		$DB_conns[$_]->{dbh}  = $dbh;
		$DB_conns[$_]->{fd}   = $dbh->mysql_fd;

		AE::log info => "MySQL connection ($_) opened";
	}

```
And run the application using EV::loop.
After a few hours (look at timestamps in attached log) I got 100% CPU utilization caused by
AnyEvent::DBI::MySQL:59(connect)>io.
Created MySQL connections not even used.

Any ideas?
[log.txt](https://github.com/powerman/perl-AnyEvent-DBI-MySQL/files/606086/log.txt)

**Comment by powerman** [comment]
No, sorry. But timing looks strange - exactly 8 hours. I'm afraid I don't have enough spare time to help you with debugging this.

**Comment by rp3u** [comment]
8 hours is a MySQL inactive timeout (wait_timeout)
mysql_auto_reconnect option has no effect at all

Here is a simple program to reproduce the callback loop:
```
#!/usr/bin/perl -w

use strict;

use AnyEvent;
use AnyEvent::Loop;
use AnyEvent::Debug;
use AnyEvent::DBI::MySQL;
use AnyEvent::Log;

AnyEvent::Debug::wrap 2;
$AnyEvent::Log::FILTER->level ("trace");

my $dbh = AnyEvent::DBI::MySQL->connect("DBI:mysql:dbname=mysql;host=127.0.0.1;port=3306",
                                        "root", "qwe",
                                        {mysql_init_command => 'SET SESSION wait_timeout = 3'}
                                        );

$dbh->{HandleError} = sub { AE::log debug => $_[0] };

AE::log debug => "Entering the Loop";
AnyEvent::Loop::run;

```

Tested on FreeBSD 10 / Ubuntu 14.04 LTS
